
OBJECT_CLASSIFIER_FOLDER = "image_classifiers"
PICTURE_CLASSIFIER_NAME = "picture_classifier.pkl"
OBJECT_BATCH_SIZE = 32
PICTURE_BATCH_SIZE = 250
OBJECT_IMG_HEIGHT = 180
OBJECT_IMG_WIDTH = 180
OBJECT_TILE_OVERLAP_COEFFICIENT = 3
OBJECT_MULTI_TILE_SIZE_MULTIPLIER = 1.5
OBJECT_EPOCHS = 5
OBJECT_THRESHOLD = 0.8
PICTURE_NUMBER_OF_HIDDEN_NEURONS = 512
PICTURE_LEARNING_RATE = 0.001
PICTURE_TRAINING_STEPS = 3000
PICTURE_DISPLAY_STEP = 100